name: nf-core-cirpipe-1.0dev
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - fastp=0.19.5
  - multiqc=1.6
  - pysam=0.15.1
  - perl=5.26.2
  - numpy=1.15.2
  - segemehl=0.3.4
  - bwa=0.7.17
  - nextflow=0.32.0
  - graphviz=2.38.0
  - bowtie=1.2.2
  - bowtie2=2.3.4.3
  - samtools=1.9
  - star=2.6.1b
  - circexplorer2=2.3.3
  - r-ggplot2=3.1.0
  - r-pheatmap=1.0.10
  - bioconductor-edger=3.22.5
  - bioconductor-deseq2=1.20.0
  - bioconductor-limma=3.36.5
  - bioconductor-chipseeker=1.16.1
  - bioconductor-fgsea=1.6.0
  - bioconductor-bsgenome.hsapiens.ucsc.hg38=1.4.1
  - bioconductor-clusterprofiler=3.8.1
  - bioconductor-reactomepa=1.24.0
  - bioconductor-pathview=1.20.0
  - r-dplyr=0.7.6
  - r-readr=1.1.1
  - r-rmarkdown=1.10
  - r-ggsci=2.9
  - r-circlize=0.4.5
  - r-rcolorbrewer=1.1_2
  - r-venndiagram=1.6.20
  - bedtools=2.27.1
  - biopython=1.72
  - bcbiogff=0.6.4
  - r-markdown=0.9
  - scipy=1.2.0
  - hisat2=2.1.0
  - htseq=0.11.2
  - unzip=6.0
  - r-ggpubr=0.2
 